// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBruQhHJpfheGW9CZdpFKSW4sNwoXxdj3c',
    appId: '1:670319268170:web:c88064c930b006911731b3',
    messagingSenderId: '670319268170',
    projectId: 'note-app-7d951',
    authDomain: 'note-app-7d951.firebaseapp.com',
    storageBucket: 'note-app-7d951.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdxLpfXms7dTcUHiq9cIUMViZDW5OZYio',
    appId: '1:670319268170:android:447973619ce0fd7c1731b3',
    messagingSenderId: '670319268170',
    projectId: 'note-app-7d951',
    storageBucket: 'note-app-7d951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5xeOIRxbA0h6n47Uj93whrz__H11OE60',
    appId: '1:670319268170:ios:bec79aa46f9535541731b3',
    messagingSenderId: '670319268170',
    projectId: 'note-app-7d951',
    storageBucket: 'note-app-7d951.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5xeOIRxbA0h6n47Uj93whrz__H11OE60',
    appId: '1:670319268170:ios:bec79aa46f9535541731b3',
    messagingSenderId: '670319268170',
    projectId: 'note-app-7d951',
    storageBucket: 'note-app-7d951.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBruQhHJpfheGW9CZdpFKSW4sNwoXxdj3c',
    appId: '1:670319268170:web:2d40647307fdf70b1731b3',
    messagingSenderId: '670319268170',
    projectId: 'note-app-7d951',
    authDomain: 'note-app-7d951.firebaseapp.com',
    storageBucket: 'note-app-7d951.firebasestorage.app',
  );
}
